name: ripcity-ticket-dispatch
services:
- name: backend
  source_dir: ripcity-backend
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
  run_command: npm start
  build_command: npm run build:full
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  
static_sites:
- name: frontend
  source_dir: rip-city-tickets-react
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
  build_command: npm run build
  output_dir: build