name: ripcity-ticket-dispatch
region: nyc
services:
- name: ripcityticketdispatch-works
  source_dir: ripcity-backend
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /api
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: mongodb+srv://doapps-01bc53ac-1f34-4b60-9b80-0c8e9e172018:u3672f9xs8n15JmF@DBMONGO-4-the-win-27af399c.mongo.ondigitalocean.com:27017/admin?retryWrites=true&w=majority&ssl=true&authSource=admin
    type: SECRET
  - key: MONGODB_URI
    value: mongodb+srv://doapps-01bc53ac-1f34-4b60-9b80-0c8e9e172018:u3672f9xs8n15JmF@DBMONGO-4-the-win-27af399c.mongo.ondigitalocean.com:27017/admin?retryWrites=true&w=majority&ssl=true&authSource=admin
    type: SECRET
  - key: TICKETMASTER_KEY
    value: "KrJ30dNjFgddGx1vUTMB7fa5GDKU0TnT"
  - key: TICKETMASTER_SECRET
    value: "I4dV25eQiAyoBwUh"
  - key: EVENTBRITE_KEY
    value: "EBBNVDS75EGKXDX2KUB3"
  - key: EVENTBRITE_SECRET
    value: "RQS25BXDXPUHQY7CCE"
  - key: OPENAI_API_KEY
    value: "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"
  - key: BUMP_TOKEN
    value: "optional-bump-token"
  - key: JWT_SECRET
    value: "your_super_secure_jwt_secret_at_least_32_characters_long"
  - key: CORS_ORIGINS
    value: https://ripcityticketdispatch.works
  - key: SENDGRID_FROM_EMAIL
    value: alerts@ripcityticketdispatch.works
  - key: FRONTEND_URL
    value: https://ripcityticketdispatch.works
  - key: TWILIO_ACCOUNT_SID
    value: ""
  - key: TWILIO_AUTH_TOKEN
    value: ""
  - key: TWILIO_FROM_NUMBER
    value: ""
  - key: EMAIL_USER
    value: ""
  - key: EMAIL_PASS
    value: ""

static_sites:
- name: ripcity-frontend
  source_dir: rip-city-tickets-react
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  output_dir: /build
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
  environment_variables:
  - key: NODE_ENV
    value: production
  - key: REACT_APP_API_URL
    value: https://ripcityticketdispatch.works/api

- name: legal-site
  source_dir: legal-site
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  routes:
  - path: /legal
  index_document: index.html
  error_document: index.html

domains:
- domain: ripcityticketdispatch.works
  type: PRIMARY
  wildcard: false
  zone: ripcityticketdispatch.works
- domain: api.ripcityticketdispatch.works
  type: ALIAS
  wildcard: false
  zone: ripcityticketdispatch.works
- domain: legal.ripcityticketdispatch.works
  type: ALIAS
  wildcard: false
  zone: ripcityticketdispatch.works
