name: ripcityticketdispatch
region: nyc
services:
- name: backend
  source_dir: ripcity-backend
  github:
    repo: josephmazzini/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm ci && npm run build:full
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /api
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: postgresql://ripcitytickets:AVNS_0qL6BX-VXiGpMySxAdo@app-f62e6190-01a4-4ba6-8bdc-eeaa9bfcd39c-do-user-23120562-0.m.db.ondigitalocean.com:25060/ripcitytickets?sslmode=require
    type: SECRET
  - key: TICKETMASTER_KEY
    type: SECRET
  - key: TICKETMASTER_SECRET
    type: SECRET
  - key: EVENTBRITE_KEY
    type: SECRET
  - key: EVENTBRITE_SECRET
    type: SECRET
  - key: STRIPE_SECRET
    type: SECRET
  - key: STRIPE
    type: SECRET
  - key: OPENAI_API_KEY
    type: SECRET
  - key: BUMP_TOKEN
    type: SECRET
  - key: JWT_SECRET
    type: SECRET
  - key: CORS_ORIGINS
    value: https://ripcityticketdispatch.works
    type: SECRET
  - key: STRIPE_ENTERPRISE_PRICE_ID
    value: "price_enterprise_monthly_9999"
    type: SECRET
  - key: FRONTEND_URL
    value: "https://ripcityticketdispatch.works"
  - key: CORS_ORIGINS
    value: "https://ripcityticketdispatch.works,https://mazzlabs.works"
  - key: STRIPE_SECRET_KEY
    value: "sk_live_your_stripe_secret_key"
    type: SECRET
  - key: STRIPE_WEBHOOK_SECRET
    value: "whsec_your_webhook_secret"
    type: SECRET
  - key: STRIPE_PRO_PRICE_ID
    value: "price_pro_monthly"
    type: SECRET
  - key: STRIPE_PREMIUM_PRICE_ID
    value: "price_premium_monthly"
    type: SECRET
  - key: STRIPE_ENTERPRISE_PRICE_ID
    value: "price_enterprise_monthly"
    type: SECRET
  - key: JWT_SECRET
    value: "your_jwt_secret_key"
    type: SECRET
  - key: FRONTEND_URL
    value: "https://ripcityticketdispatch.works"

domains:
- domain: api.ripcityticketdispatch.works
  type: PRIMARY
  wildcard: false
  zone: ripcityticketdispatch.works
- domain: ripcityticketdispatch.works
  type: ALIAS
  wildcard: false
  zone: ripcityticketdispatch.works
