name: rip-city-api
region: nyc
services:
- name: api
  source_dir: rip-city-backend
  github:
    repo: Mazzlabs/Mazzlabs.github.io
    branch: main
    deploy_on_push: true
  run_command: node dist/server.js
  build_command: npm ci && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: TICKETMASTER_API_KEY
    value: "your-api-key-here"
    type: SECRET
  - key: CORS_ORIGINS
    value: "https://ripcityticketdispatch.works,https://mazzlabs.works"

domains:
- domain: api.ripcityticketdispatch.works
  type: PRIMARY
  wildcard: false
  zone: ripcityticketdispatch.works
- domain: ripcityticketdispatch.works
  type: ALIAS
  wildcard: false
  zone: ripcityticketdispatch.works
