name: ripcity-ticket-dispatch
region: nyc
services:
- name: ripcityticketdispatch-works
  source_dir: ripcity-backend
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build:full
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /api
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: mongodb+srv://doadmin:j3Vo8py57290S1nP%3Dadminpw@DBMONGO-4-the-win-27af399c.mongo.ondigitalocean.com/ripcitytickets?retryWrites=true&w=majority&ssl=true&authSource=admin
    type: SECRET
  - key: MONGODB_URI
    value: mongodb+srv://doadmin:j3Vo8py57290S1nP%3Dadminpw@DBMONGO-4-the-win-27af399c.mongo.ondigitalocean.com/ripcitytickets?retryWrites=true&w=majority&ssl=true&authSource=admin
    type: SECRET
  - key: TICKETMASTER_KEY
    type: SECRET
  - key: TICKETMASTER_SECRET
    type: SECRET
  - key: EVENTBRITE_KEY
    type: SECRET
  - key: EVENTBRITE_SECRET
    type: SECRET
  - key: STRIPE_SECRET
    type: SECRET
  - key: OPENAI_API_KEY
    type: SECRET
  - key: BUMP_TOKEN
    type: SECRET
  - key: JWT_SECRET
    type: SECRET
  - key: CORS_ORIGINS
    value: https://ripcityticketdispatch.works
  - key: TWILIO_ACCOUNT_SID
    type: SECRET
  - key: TWILIO_AUTH_TOKEN
    type: SECRET
  - key: TWILIO_PHONE_NUMBER
    type: SECRET
  - key: SENDGRID_API_KEY
    type: SECRET
  - key: SENDGRID_FROM_EMAIL
    value: alerts@ripcityticketdispatch.works
  - key: STRIPE_PRO_PRICE_ID
    type: SECRET
  - key: STRIPE_PREMIUM_PRICE_ID
    type: SECRET
  - key: STRIPE_ENTERPRISE_PRICE_ID
    type: SECRET
  - key: STRIPE_WEBHOOK_SECRET
    type: SECRET
  - key: FRONTEND_URL
    value: https://ripcityticketdispatch.works

- name: ripcity-frontend
  source_dir: rip-city-tickets-react
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  run_command: npx serve -s build -p $PORT
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: REACT_APP_API_URL
    value: https://api.ripcityticketdispatch.works
  - key: PORT
    value: "3000"

static_sites:
- name: legal-site
  source_dir: legal-site
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  routes:
  - path: /legal
  index_document: index.html
  error_document: index.html

domains:
- domain: ripcityticketdispatch.works
  type: PRIMARY
  wildcard: false
  zone: ripcityticketdispatch.works
- domain: api.ripcityticketdispatch.works
  type: ALIAS
  wildcard: false
  zone: ripcityticketdispatch.works
- domain: legal.ripcityticketdispatch.works
  type: ALIAS
  wildcard: false
  zone: ripcityticketdispatch.works
