# DigitalOcean App Platform Configuration
# Rip City Ticket Dispatch - Single Service Architecture
name: ripcity-ticket-dispatch
region: nyc

services:
- name: ripcityticketdispatch-works
  source_dir: ripcity-backend
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  run_command: npm run start:https
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /api
    preserve_path_prefix: true
  - path: /health
  - path: /
    preserve_path_prefix: true
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: ENABLE_HTTPS
    value: "true"
  - key: HTTPS_PORT
    value: "8443"
  - key: DATABASE_URL
    value: mongodb+srv://doadmin:7c195P84CqA6Nf2a@db-mongo-nyc-888-9dab7096.mongo.ondigitalocean.com/admin?retryWrites=true&w=majority&ssl=true&authSource=admin
    type: SECRET
  - key: MONGODB_URI
    value: mongodb+srv://doadmin:7c195P84CqA6Nf2a@db-mongo-nyc-888-9dab7096.mongo.ondigitalocean.com/admin?retryWrites=true&w=majority&ssl=true&authSource=admin
    type: SECRET
  - key: TICKETMASTER_KEY
    value: "KrJ30dNjFgddGx1vUTMB7fa5GDKU0TnT"
  - key: TICKETMASTER_SECRET
    value: "I4dV25eQiAyoBwUh"
  - key: EVENTBRITE_KEY
    value: "EBBNVDS75EGKXDX2KUB3"
  - key: EVENTBRITE_SECRET
    value: "RQS25BXDXPUHQY7CCE"
  - key: OPENAI_API_KEY
    value: "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"
  - key: BUMP_TOKEN
    value: "optional-bump-token"
  - key: JWT_SECRET
    value: "your_super_secure_jwt_secret_at_least_32_characters_long"
  - key: CORS_ORIGINS
    value: https://ripcityticketdispatch.works
  - key: SENDGRID_FROM_EMAIL
    value: alerts@ripcityticketdispatch.works
  - key: FRONTEND_URL
    value: https://ripcityticketdispatch.works
  - key: TWILIO_ACCOUNT_SID
    value: ""
  - key: TWILIO_AUTH_TOKEN
    value: ""
  - key: TWILIO_FROM_NUMBER
    value: ""
  - key: EMAIL_USER
    value: ""
  - key: EMAIL_PASS
    value: ""
  # React environment variables for build
  - key: REACT_APP_API_URL
    value: https://ripcityticketdispatch.works/api
  - key: PUBLIC_URL
    value: https://ripcityticketdispatch.works

static_sites:
- name: legal-site
  source_dir: legal-site
  github:
    repo: J-mazz/ripcityticketdispatch.works
    branch: main
    deploy_on_push: true
  routes:
  - path: /legal
  index_document: index.html
  error_document: index.html

domains:
- domain: ripcityticketdispatch.works
  type: PRIMARY
  wildcard: false
  zone: ripcityticketdispatch.works
- domain: api.ripcityticketdispatch.works
  type: ALIAS
  wildcard: false
  zone: ripcityticketdispatch.works
- domain: legal.ripcityticketdispatch.works
  type: ALIAS
  wildcard: false
  zone: ripcityticketdispatch.works
