doc: rip-city-ticket-dispatch
token: ${{ secrets.BUMP_TOKEN }}
file: docs/openapi.yaml
auto_create: true

# Hub configuration for Bump.sh
hub:
  name: "Rip City Ticket Dispatch"
  description: "Portland-focused ticket deal monitoring platform with real-time alerts and AI-powered deal scoring"
  logo: "https://ripcityticketdispatch.works/logo512.png"
  url: "https://ripcityticketdispatch.works"
  
# Deployment settings
deploy:
  validation: true
  overlay: true
  
# Git integration
git:
  auto_deploy: true
  branch_name: main
